import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  contentHeaderContainer: {
    backgroundColor: '#1a1b1e',
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'column',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  headerContainerContactList: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingTop: 20,
    alignItems: 'center',
  },
  contactHeaderTextStyle: {
    fontWeight: '800',
    fontSize: 20,
    color: 'white',
  },
  renderItemContainerStyle: {flexDirection: 'column'},
  renderItemTopViewStyle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'white',
  },
  renderItemNameInputStyle: {
    width: '100%',
    fontWeight: '900',
    fontSize: 20,
    color: 'white',
  },
  topViewStyles: {height: '100%', backgroundColor: '#404040'},
  topButtonsEditAdd: {
    flexDirection: 'row',
    borderWidth: 2,
    alignItems: 'center',
    alignSelf: 'center',
    alignContent: 'space-between',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 10,
    backgroundColor: 'white',
    shadowOpacity: 0.5,
    shadowRadius: 4,
    height: 40,
  },
  addContactTextInputStyles: {
    borderColor: 'white',
    borderBottomWidth: 2,
    borderRadius: 10,
    margin: 20,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingBottom: 10,
    fontWeight: '400',
    fontSize: 20,
    color: 'white',
    borderBottomColor: 'white',
  },
  addContactTextInputNumberStyle: {
    borderColor: 'white',
    borderBottomWidth: 2,
    borderRadius: 10,
    margin: 20,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
    top: -10,
    fontWeight: '400',
    fontSize: 20,
    color: 'white',
    borderBottomColor: 'white',
  },
  addButtonTextInputStyle: {
    borderColor: 'white',
    borderBottomWidth: 2,
    borderRadius: 10,
    margin: 20,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
    fontWeight: '400',
    fontSize: 20,
    color: 'white',
    borderBottomColor: 'white',
    flex: 1,
  },
  buttonStyleAddContactUpdateContact: {
    paddingBottom: 30,
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 30,
  },
  textStyleEmptyContact: {
    alignSelf: 'center',
    fontWeight: '600',
    fontSize: 20,
    paddingTop: 20,
    color: 'white',
  },
  addButtonContainerStyle: {flexDirection: 'row'},
  updateNumberStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkIconStyle: {
    position: 'absolute',
    left: 340,
    right: 0,
    justifyContent: 'center',
    top: Platform.OS === 'ios' ? 20 : 35,
  },
  addContactStyle: {
    backgroundColor: '#1a1b1e',
    margin: 10,
    borderRadius: 10,
    paddingBottom: -10,
  },
  container: {
    margin: 15,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  searchBar__unclicked: {
    padding: 10,
    flexDirection: 'row',
    width: '95%',
    backgroundColor: '#d9dbda',
    borderRadius: 15,
    alignItems: 'center',
  },
  searchBar__clicked: {
    padding: 10,
    flexDirection: 'row',
    width: '80%',
    backgroundColor: '#d9dbda',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  input: {
    fontSize: 20,
    marginLeft: 10,
    width: '90%',
  },
  deleteEditContainer: {flexDirection: 'row'},
});

export default styles;
