import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  addressContainerTextInputStyle: {
    minWidth: '95%',
    color: 'white',
    fontSize: 20,
    marginHorizontal: 10,
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    paddingVertical: 10,
    margin: 10,
  },
  lineSeperatorStyles: {
    height: 1,
    marginTop: 30,
    marginHorizontal: 10,
  },
  contactIconContainerStyle: {alignItems: 'center', flex: 1},
  contactIconStyle: {
    margin: 15,
    padding: 20,
    backgroundColor: '#1a1b1e',
    top: 20,
    borderRadius: 15,
    flexDirection: 'row',
  },
  contactInfoContainerStyle: {
    backgroundColor: '#1a1b1e',
    height: '20%',
    margin: 20,
    borderRadius: 20,
    flexDirection: 'row',
    flex: 1,
    padding: 20,
    justifyContent: 'space-between',
  },
  addressLeftIconStyle: {width: 30, alignSelf: 'center'},
  addressTextStyle: {
    color: 'white',
    fontSize: 15,
    alignSelf: 'center',
    marginHorizontal: 20,
    maxWidth: '70%',
  },
  addressRightIconStyle: {
    width: 30,
    alignSelf: 'center',
  },
  containerStyle: {backgroundColor: '#404040', flex: 1},
  circleContainerStyle: {
    backgroundColor: 'black',
    height: 100,
    width: 100,
    alignSelf: 'center',
    marginTop: '10%',
    borderRadius: 50,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  circleTextStyles: {
    color: 'white',
    fontSize: 60,
    alignSelf: 'center',
  },
  userNameStyles: {
    color: 'white',
    fontSize: 30,
    alignSelf: 'center',
    top: 10,
  },
  userNumberContainer: {flexDirection: 'row', alignSelf: 'center'},
  userNumberStyles: {
    color: 'white',
    fontSize: 30,
    alignSelf: 'center',
    top: 10,
  },
  editNumberIconStyle: {
    alignSelf: 'center',
    top: Platform.OS === 'ios' ? 10 : 15,
    left: 10,
  },
  updateNumberStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addButtonTextInputStyle: {
    borderColor: 'white',
    borderBottomWidth: 2,
    borderRadius: 10,
    margin: 20,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
    fontWeight: '400',
    fontSize: 20,
    color: 'white',
    borderBottomColor: 'white',
    flex: 1,
  },
  checkIconStyle: {
    position: 'absolute',
    left: 340,
    right: 0,
    justifyContent: 'center',
    top: Platform.OS === 'ios' ? 20 : 35,
  },
  contactIconContainer: {flexDirection: 'row'},
  visibleMessageContainerStyle: {
    backgroundColor: '#1a1b1e',
    marginTop: 20,
    marginHorizontal: 20,
    borderRadius: 20,
    minHeight: '15%',
    padding: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  visibleContainerTextInputStyle: {
    maxWidth: '75%',
    minWidth: '75%',
    color: 'white',
    fontSize: 20,
    marginHorizontal: 10,
  },
  sendMessageIconStyle: {alignSelf: 'center', margin: 20},
  visibleAddressContainerStyle: {
    backgroundColor: '#1a1b1e',
    marginVertical: 20,
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 3,
    flexDirection: 'column',
    paddingVertical: 20,
    flex: 1,
  },
  updateAddressButtonStyle: {marginTop: 10, width: '50%', alignSelf: 'center'},
});

export default styles;
