import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  contentHeaderContainer: {
    backgroundColor: '#ff4081',
    width: '100%',
    height: 50,
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  contactHeaderTextStyle: {
    fontWeight: '600',
    fontSize: 20,
    color: 'white',
  },
  renderItemContainerStyle: {flexDirection: 'column'},
  renderItemTopViewStyle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  renderItemNameInputStyle: {width: '100%', fontWeight: '900', fontSize: 20},
  topViewStyles: {height: '100%'},
  topButtonsEditAdd: {
    flexDirection: 'row',
    borderWidth: 2,
    alignItems: 'center',
    alignSelf: 'center',
    alignContent: 'space-between',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 10,
    backgroundColor: '#ff4081',
    shadowOpacity: 0.5,
    shadowRadius: 4,
    height: 40,
  },
  addContactTextInputStyles: {
    borderColor: 'black',
    borderBottomWidth: 2,
    borderRadius: 10,
    margin: 20,
    marginBottom: 0,
    paddingHorizontal: 20,
    paddingBottom: 10,
    fontWeight: '800',
    fontSize: 20,
  },
  addContactTextInputNumberStyle: {
    borderColor: 'black',
    borderBottomWidth: 2,
    borderRadius: 10,
    margin: 20,
    paddingHorizontal: 20,
    paddingBottom: 10,
    fontWeight: '800',
    fontSize: 20,
  },
  buttonStyleAddContactUpdateContact: {padding: 20},
  textStyleEmptyContact: {
    alignSelf: 'center',
    fontWeight: '600',
    fontSize: 20,
    paddingTop: 20,
  },
});

export default styles;
